name: Update M3U Playlist

on:
  schedule:
    - cron: '0 3 * * 5'  # Every day at 03:00 UTC
  workflow_dispatch:

# Grant write permissions to the GITHUB_TOKEN
permissions:
  contents: write  # Allows git push

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3  # Uses GITHUB_TOKEN by default

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Run filter script
        run: python source.py

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add playlist.m3u
          git commit -m "Update playlist"
          git push
